### ISSUE TITLE
[Feature Track] Knative Eventing Kafka Operator

### ISSUE THREAD

**Issue by matzew** [knative-extensions/eventing-kafka-broker#1781]
## Problem

For Knative's Eventing components for Apache Kafka there is no well defined mechanism to install these in a combined and structuerd way. The upstream `knative/operator` has only support for supporting a number of sources, including the `KafkaSource`. It does leave out the `KafkaChannel` and the _Kafka-based_ `Broker` implementation. It is also questionable if hammering these types into the `KnativeEventing` API from the operator does make sense.

## Description

An opinionated Knative Eventing Kafka operator is needed that focuses on installing the various components from the "Knative Kafka Broker" repository:
* `KafkaSink` 
* `Broker` implementation based on Apache Kafka
* `KafkaSource` Java Data Plane implementation
* `KafkaChannel` Java Data Plane implementation
* `KafkaSink` 

Being an opinionated Operator it should also install the Eventing Core APIs, without its optional components, such as the `InMemoryChannel`.  

## Feature Track

https://hackmd.io/@matzew/ryALMZdaY

## Why

1. Provide a focus Operator that installs everything needed for Knative Kafka out of the box
2. Avoids overloading the `knative/operator` with more feature flags and making its API less usable or maintainable 

## Exit Criteria

Operator being implemented...

**Comment by csantanapr** [comment]
I think it would be bad to have another operator for Kafka broker. In my honest opinion this should be part of the single Knative Operator. 
it can can be part of operator eventing crd it’s own operator crd for kafka..but it should remain as the one knative operator to install and upgrade any core knative components including rabbitmq broker
