### ISSUE TITLE
Deprecate and migrate KafkaChannel secret format to Broker/Sink secret format

### ISSUE THREAD

**Issue by pierDipi** [knative-extensions/eventing-kafka-broker#2231]
**Problem**

The KafkaChannel secret format is using some different keys, as discussed in https://github.com/knative-sandbox/eventing-kafka-broker/issues/2213, we should align it to the Broker and Sink format.
In https://github.com/knative-sandbox/eventing-kafka-broker/pull/2224 we added support for the old format only.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
- users (maintainers as well)

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**

/area channel
/triage accepted

**Comment by aliok** [comment]
I thought this is working out of the box.

Did you remove the code that reads the new format with https://github.com/knative-sandbox/eventing-kafka-broker/pull/2224 @pierDipi ?

We should fallback if for example, `protocol` is missing.

**Comment by pierDipi** [comment]
I didn't remove the code (it's still there because we need it for broker) but I didn't add the fallback logic
