### ISSUE TITLE
KafkaSinks ContentMode ignored

### ISSUE THREAD

**Issue by creydr** [knative-extensions/eventing-kafka-broker#2951]
**Describe the bug**

The default content mode when installing a Kafka Sink is `binary`:

https://github.com/knative-sandbox/eventing-kafka-broker/blob/9459144e95bd13df164340970a96b58a2761daa4/control-plane/pkg/apis/eventing/v1alpha1/kafka_sink_defaults.go#L28-L32

In #2932 we migrated an e2e test for the Sink, with a job for publishing to the Sink using `structured` content mode, without changing the default in Sink before. This test still succeeds, so 

* No verification is happening, or
* There is a bug in the sink implementation for changing content mode

 **To Reproduce**
Steps to reproduce the behavior.

Run the `TestBrokerTirggersSink` test from #2932

 **Knative release version**
On main branch (today with 5475bd8641cb0b732dca4ef1adc2c67d0d68e358)

**Comment by debasishbsws** [comment]
When I am trying to run `TestBrokerTirggersSink` test. it is giving output like  
```
?       knative.dev/eventing-kafka-broker/test/e2e_new  [no test files]
```
what should I do?

**Comment by pierDipi** [comment]
@debasishbsws how are you running the test?

**Comment by pierDipi** [comment]
you need to specify also tags `go test -tags=e2e ...`

**Comment by debasishbsws** [comment]
now it shows `ERROR: Broker class is not defined. Specify it with 'BROKER_CLASS' env var.`

**Comment by pierDipi** [comment]
You can run them like this:

```
SYSTEM_NAMESPACE=knative-eventing BROKER_CLASS=Kafka go test -tags=e2e -run ^TestBrokerTriggersSink$ .test/e2e_new/
```

**Comment by debasishbsws** [comment]
ok thanks
