### ISSUE TITLE
Expose Kafka record offset and partition

### ISSUE THREAD

**Issue by EndPositive** [knative-extensions/eventing-kafka-broker#3072]
**Problem**
When the offset is known to the consumer, it is no longer reliant on ordered consumption of the events. E.g. a consumer could use the offset+partition to order the events by itself.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Event consumer (developer)

**Exit Criteria**
The incoming HTTP request contains the offset and partition information.

**Time Estimate (optional):**
1 day

**Comment by Cali0707** [comment]
Hi @EndPositive - sorry for the delay getting to this issue!

We're currently working on it, and are wondering if using CloudEvent Extension Attributes for offset and partition would work for your use case? These would be set as headers on the http request, with a `ce-*` prefix. We think that using the extension attributes could be useful as it would also allow you to define filters in the triggers based on conditions on them.

WDYT? Would this work for you, or do you strictly want http headers and no extension attributes?

**Comment by EndPositive** [comment]
CE extension sounds good!
