### ISSUE TITLE
Dispatcher stop consuming from one partition in one consumer group

### ISSUE THREAD

**Issue by apenen** [knative-extensions/eventing-kafka-broker#3085]
**Describe the bug**
Dispatcher stops consuming from a partition in one consumer group:

![image](https://github.com/knative-sandbox/eventing-kafka-broker/assets/9284027/681bd125-7edc-4b0c-ac8d-d47410664a90)
![image](https://github.com/knative-sandbox/eventing-kafka-broker/assets/9284027/031172af-0515-488e-8f6a-faa5709fdb1c)

 **Expected behavior**
Dispatcher continues consuming from a partition

 **To Reproduce**
We have 7 brokers with 154 triggers in total. KafkaTopics have 6 partitions and we have 6 dispatchers. We move many messages:
![image](https://github.com/knative-sandbox/eventing-kafka-broker/assets/9284027/bbc808e6-a297-4056-8e75-39363c58d6a4)

 
 **Knative release version**
 knative version: 1.9.7
 knative-kafka-broker-dispatcher:v1.9.4

 **Additional context**
Most of the time the problem occurs with the same ce-type, which is consumed by several triggers.

**Comment by pierDipi** [comment]
@apenen does it happen on [Triggers with ordered or unordered](https://knative.dev/docs/eventing/brokers/broker-types/kafka-broker/#configuring-the-order-of-delivered-events) delivery? or both?

**Comment by apenen** [comment]
@pierDipi We only have unordered triggers.

**Comment by pierDipi** [comment]
@apenen can you upgrade eventing-kafka-broker to 1.9.6, this commit might fix your issue: https://github.com/knative-sandbox/eventing-kafka-broker/commit/44c60b11c471210c372a26a1beb10500d181ad7b but it was backported in 1.9.6

**Comment by apenen** [comment]
We have updated to version 1.9.6. I'll keep you informed.

**Comment by apenen** [comment]
It's happening again with version 1.9.6:
![image](https://github.com/knative-sandbox/eventing-kafka-broker/assets/9284027/01a48cab-191b-4bf4-976a-860d314b4b0f)

**Comment by apenen** [comment]
@pierDipi, it seems that it doesn't play as often anymore...
Even so, it would be nice to know why the one shown in the previous comment happened in version 1.9.6.

**Comment by pierDipi** [comment]
@apenen thanks for the update!

we're trying to reproduce in our long running environment but so far we haven't seen this behavior, we found this issue: https://github.com/knative-sandbox/eventing-kafka-broker/pull/3103 while trying to reproduce but it doesn't directly explain this particular issue because even without that fix it should be making progress when there are events and it should retry committing the offset by consuming records.

have you seen any error/warning logs on the dispatcher when this happens?

**Comment by apenen** [comment]
We see the following at about the same time the lag starts to increase...
![image](https://github.com/knative-sandbox/eventing-kafka-broker/assets/9284027/71023bd2-0aee-42bb-acea-6cbc8d516e25)

**Comment by pierDipi** [comment]
@apenen can you share kafka-broker-dispatcher metrics?

These are the metrics we expose on the receiver and dispatcher (assuming Promtheus operator is used), in particular, I'm interested in `event_count_1_total{job="kafka-broker-dispatcher-sm-service", namespace="knative-eventing"}` grouped by `response_code`

<b style="font-weight:normal;" id="docs-internal-guid-65e728ba-7fff-980d-bbf3-d6452c7e1e46"><h1 dir="ltr" style="line-height:1.2;margin-top:20pt;margin-bottom:6pt;"><span style="font-size:20pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Knative Kafka Broker</span></h1><h2 dir="ltr" style="line-height:1.2;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Knative Kafka Broker metrics</span></h2><br /><p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">You can use the following metrics to debug and visualize the performance of Kafka Broker.</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Metric | Description | Type | Tags | Unit
-- | -- | -- | -- | --
event_count_1_total{job="kafka-broker-receiver-sm-service", namespace="knative-eventing"} | Number of events received by a Broker | Counter | name (broker name)namespace_name (broker namespace)event_type (event type)response_code (HTTP response code returned by the Broker)response_code_class (HTTP response code class returned by the Broker: 2xx, 3xx, 4xx, 5xx) | Dimensionless
event_dispatch_latencies_ms_bucket{job="kafka-broker-receiver-sm-service", namespace="knative-eventing"} | The time spent dispatching an event to a Kafka cluster | Histogram | name (Broker name)namespace_name (Broker namespace)event_type (event type)response_code (HTTP response code returned by the Broker)response_code_class (HTTP response code class returned by the Broker: 2xx, 3xx, 4xx, 5xx) | Milliseconds

</div></b>

<b style="font-weight:normal;" id="docs-internal-guid-2e788978-7fff-e94b-f00c-cedcacd7a28a"><h2 dir="ltr" style="line-height:1.2;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Knative Kafka Trigger metrics</span></h2><p dir="ltr" style="line-height:1.2;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">You can use the following metrics to debug and visualize the performance of Kafka triggers.</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Metric | Description | Type | Tags | Unit
-- | -- | -- | -- | --
event_count_1_total{job="kafka-broker-dispatcher-sm-service", namespace="knative-eventing"} | Number of events dispatched by a Trigger to a subscriber | Counter | consumer_name (Trigger name)namespace_name (trigger namespace)name (Broker name)event_type (event type)response_code (HTTP response code returned by the Trigger subscriber service)response_code_class (HTTP response code class returned by the Trigger subscriber service: 2xx, 3xx, 4xx, 5xx) | Dimensionless
event_dispatch_latencies_ms_bucket{job="kafka-broker-dispatcher-sm-service", namespace="knative-eventing"} | The time spent dispatching an event to a subscriber | Histogram | event_type (event type)consumer_name (Trigger name)namespace_name (Trigger namespace)name (Broker name)response_code (HTTP response code returned by the Trigger subscriber service)response_code_class (HTTP response code class returned by the Trigger subscriber service: 2xx, 3xx, 4xx, 5xx) | Milliseconds
event_processing_latencies_ms_bucket{job="kafka-broker-dispatcher-sm-service", namespace="knative-eventing"} | The time spent processing and filtering an event | Histogram | event_type (event type)consumer_name (Trigger name)namespace_name (Trigger namespace)name (Broker name) | Milliseconds

</div></b>

**Comment by apenen** [comment]
I have been very busy this week. I will try to give you all the information as soon as possible.
