### ISSUE TITLE
Job stuck while auto migration from consolidated channel

### ISSUE THREAD

**Issue by kiranmenon** [knative-extensions/eventing-kafka-broker#3092]
**Describe the bug**
In my setup, I am using MTChannel based broker backed by a KafkaChannel. And Im trying to migrate to eventing-kafka-broker. Now while trying to run the auto migration job following the [doc](https://github.com/knative-sandbox/eventing-kafka-broker/tree/knative-v1.9.4/docs/channel), Im seeing that the one of the 2 k8s Job "kafka-controller-post-install " never reaches  'Completed' state. Also I see below error in the logs:
`[opc@knative-eventing]$ kubectl -n knative-eventing logs kafka-controller-post-install-9qvd7 --previous
{"severity":"EMERGENCY","timestamp":"2023-05-19T11:01:48.281685318Z","logger":"kafka-broker-post-install","caller":"post-install/main.go:46","message":"source dispatcher deletion failed: failed while waiting for statefulset to come up: timed out waiting for the condition","commit":"d50ecb1-dirty","stacktrace":"main.main\n\tknative.dev/eventing-kafka-broker/control-plane/cmd/post-install/main.go:46\nruntime.main\n\truntime/proc.go:250"}
`

 **Expected behavior**
The auto migration job should complete its tasks, migrates the configmaps, delete old deployments etc.

 **To Reproduce**

- Deploy knative-eventing core and consolidated channel (I used v1.8.1)
- Create an MTchannelbroker based on a kafka-channel, test the eventing.
- Upgrade to v1.9.6. Deploy the knative-eventing core(v1.9.6) and then the eventing-kafka-broker (v1.9.4)
- Create the kafka-controller-post-install job

 **Knative release version**
knative-eventing-core v.1.9.6
eventing-kafka-broker v1.9.4

**Comment by pierDipi** [comment]
This is due to the fact that you don't have KafkaSource installed and the job is assuming a kafka-source-dispatcher will eventually exist
