### ISSUE TITLE
Eventing TLS: use composite prober everywhere

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3141]
**Problem**
When https://github.com/knative-sandbox/eventing-kafka-broker/pull/3125, https://github.com/knative-sandbox/eventing-kafka-broker/pull/3123, and https://github.com/knative-sandbox/eventing-kafka-broker/pull/3122 get merged in, we will need to update the controllers so that a prober with TLS support is created if the `Status.Address` is an https address. To do this we are introducing a composite prober, and will transition to using that as the main prober everywhere we use probers currently.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
- [x] https://github.com/knative-sandbox/eventing-kafka-broker/issues/3176
- [x] https://github.com/knative-sandbox/eventing-kafka-broker/issues/3187
- [x] https://github.com/knative-sandbox/eventing-kafka-broker/issues/3188
- [x] https://github.com/knative-sandbox/eventing-kafka-broker/issues/3189
- [ ] https://github.com/knative-sandbox/eventing-kafka-broker/issues/3190

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 1

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by Cali0707** [comment]
@pierDipi can you add this to the Eventing TLS project?

**Comment by Cali0707** [comment]
@pierDipi to clarify on requirements for this feature, should we use the prober with TLS when:
1. The `Status.Address` is https or
2. `Status.Addresses` contains an https address (but `Status.Address` may not necessarily)
Also, to further complicate things, should we be using both a prober without TLS on the http address and a prober with TLS on the https address when we are in TLS permissive?

**Comment by pierDipi** [comment]
Good question, I think I would do this:
>  should we be using both a prober without TLS on the http address and a prober with TLS on the https address when we are in TLS permissive?

This will gives us the confidence that when a resource is ready whatever is set on the `Addressable` is correct in terms of - readiness to receive events
- correct wrt CA certs

**Comment by pierDipi** [comment]
Ideallly, we have a "prober" that takes an `Addressable` type (which contains a list of addresses) and probes them according to the scheme (so that we can re-use such composite prober in all the places we need probing)

**Comment by pierDipi** [comment]
I'd say this
> only setting the status to true if both are addressable

In particular, we will only set the `ProbeStatus` condition to true if _all_ addresses in `status.addresses` are reachable / addressable

**Comment by pierDipi** [comment]
> @pierDipi when we use the composite prober, we need a port for both the http and https probe endpoints. We are currently getting the port here: https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/control-plane/pkg/reconciler/broker/controller.go#L97 with `env.IngressPodPort`. Would this port be for http or https, and how would we find the port for the other?

I think, we would need a new env variable for the HTTPS port
