### ISSUE TITLE
Kafkachannels are always in NOTREADY state with reason 'ProbeStatus'

### ISSUE THREAD

**Issue by rakhya** [knative-extensions/eventing-kafka-broker#3165]
Hi, We migrated from knative distributed kafka channel to New kafkachannel as part of knative 1.9 upgrade about 2 months ago. Here are tools we are running

1. EKS - 1.24
2. Istio - 1.15.7
3. Strimzi Kafka Operator - 0.29
4. Strimzi Kafka Cluster - 3.2
5. Knative Operator - 1.9.5
6. Knative Eventing - 1.9.7
7. Knative Serving - 1.9.3
8. Knative Eventing KafkaChannel - 1.9.6

We upgraded knative from v1.3 to v1.9, replaced distributed kafkachannel (v1.3) with new eventing Kafkachannel (v1.9.6) in our dev environment. Configured replica counts for the following resources

1. Strimzi Kafka brokers - 24
2. Strimzi Kafka zookeepers - 3
3. Kafka-channel-dispatcher replicas - 60
4. Kafka-channel-receiver replicas - 30
5. Kafka-controller replicas - 5
6. Total kafka-channels deployed across different namespaces in the cluster - 400+

Almost 150 kafkachannels are always in 'ProbeStatus' failed state. And remaining Kafkachannels toggle b/w READY and NOTREADY state due to the same reason. Due to this the corresponding Subscriptions are also in NOTREADY state.

Could you pls let me know what could be the issue here?

**Comment by pierDipi** [comment]
@rakhya are you using Istio with Knative Eventing?

can you please paste the logs from the kafka-controller? `kubectl logs -n knative-eventing -l=app=kafka-controller -f`

**Comment by rakhya** [comment]
any update here?

**Comment by kumarakannan** [comment]
@pierDipi We are planning to upgrade to knative 1.11 and we can plan to use KafkaChannel during this maintenance window. Do we have an update ?

**Comment by kumarakannan** [comment]
@pierDipi , Can you please look into it ?
