### ISSUE TITLE
Java Code Formatter

### ISSUE THREAD

**Issue by Leo6Leo** [knative-extensions/eventing-kafka-broker#3166]
**Problem**
I was working on a Java ticket these days, and found that the format of our java codebase sometime is not consistent. 
Therefore, I am trying to propose a Java formatter for the team.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Knative developers

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.
- The formatter is easy to use for developers
- The CI tests should be configured as well. 
https://github.com/knative-sandbox/eventing-kafka-broker/blob/93b0ecb56d9550f7cff6f0089073e935fe2a3cd3/hack/update-codegen.sh#L80-L83

**Time Estimate (optional):** 
1

**Additional context (optional)**
The fotmatter I am proposing is called [Spotless](https://github.com/diffplug/spotless).

The Pros for choosing Spotless:
- Just run mvn spotless:apply does magic
- It is widely used, and actively been maintained!
- Can be integrated with CI testing
- It supports [many different](https://github.com/diffplug/spotless/tree/main/plugin-maven#google-java-format) formatting policy (google java style, eclipse jdt...)
- Support with IntelliJ IDEA and VSCode

**Comment by pierDipi** [comment]
@debasishbsws this will help us for formatting Java code, if you have got opinions and thoughts on this, feel free to comment, like if the proposed tool would work for you, etc

**Comment by debasishbsws** [comment]
I think it will be a good idea to have a formatter.
I know about checkstyle that is a linting tool for java, but it doesn't work as a formatter ig.
Spotless looks like a cool to work with.
