### ISSUE TITLE
Implement the auto-create feature flag for the Apache Kafka backed Knative Channel 

### ISSUE THREAD

**Issue by matzew** [knative-extensions/eventing-kafka-broker#3181]
With the following two PRs in place:

* https://github.com/knative/eventing/pull/7023
* https://github.com/knative/eventing/pull/7034

We can add support for "event auto create" also for the data plane of the Apache Kafka backed Knative Channel .

**Comment by matzew** [comment]
related: https://github.com/knative-sandbox/eventing-kafka-broker/issues/3174

**Comment by Cali0707** [comment]
@pierDipi for this issue it looks like I should be using the KubernetesClient from fabric.io. However, the KubernetesClient we are using doesn't have the Knative extension installed, and the Knative extension in fabric.io seems to be out of date (it's on v0.34.0 of Knative).

Should I
1. Update the Knative models in fabric.io and install the Knative extension into our project
2. Create a class which implements the needed methods for EventTypes

My impression is that 2 would be faster and easier, but I am not sure it would be the best option - WDYT?

**Comment by pierDipi** [comment]
The other question is about caching, we cannot make a k8s remove call on each received event, so we need some form of caching, in Go we use the listers (+ watcher) as cache, do we have the same in Fabric that we can leverage?

**Comment by Cali0707** [comment]
> The other question is about caching, we cannot make a k8s remote call on each received event, so we need some form of caching, in Go we use the EventType listers (+ watcher) as cache, do we have the same in Fabric that we can leverage?

@pierDipi it looks like there are Listers in fabric: https://javadoc.io/doc/io.fabric8/kubernetes-client/4.6.4/io/fabric8/kubernetes/client/informers/cache/Lister.html

I am going to try and use one of those
