### ISSUE TITLE
Eventing TLS: E2E tests for broker, channel and sink TLS key pair rotation

### ISSUE THREAD

**Issue by pierDipi** [knative-extensions/eventing-kafka-broker#3221]
**Problem**

We should have rekt-based E2E tests that tests TLS key pairs rotation for each individual component.

We should make use of:
- https://github.com/knative-sandbox/reconciler-test/pull/548
- https://github.com/knative-sandbox/reconciler-test/pull/549

Each test flow would be:
- Install target resources
- rotate certs (https://github.com/knative-sandbox/reconciler-test/pull/549)
- verify new rotated certs are used (https://github.com/knative-sandbox/reconciler-test/pull/548)

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**

- related to https://github.com/knative/eventing/issues/7039

For Channel and Sink tests, this issue depends on:
- https://github.com/knative-sandbox/eventing-kafka-broker/issues/3188
- https://github.com/knative-sandbox/eventing-kafka-broker/issues/3189

**Subtasks**

- [x] #3373 
- [x] #3374 
- [x] #3375

**Comment by pierDipi** [comment]
cc @Leo6Leo this is for testing E2E the Vertx key pair rotation you have implemented, in case you some time to dedicate, here is an example PR: https://github.com/knative/eventing/pull/7103 (not yet fully working but that should give you an high-level idea)

**Comment by Cali0707** [comment]
@pierDipi the prober for sink and channels does not yet support TLS or rotating the CA Certs, so I am not sure if they will reconcile properly

**Comment by Cali0707** [comment]
@Leo6Leo the test for the sink should also be ready to go now - just waiting on the channel

**Comment by Leo6Leo** [comment]
This issue has been splited to 3 different sub-tasks. @pierDipi Could you update the issue description?
- [ ] #3373 
- [ ] #3374 
- [ ] #3375

**Comment by pierDipi** [comment]
Can you add those new issues to the project https://github.com/orgs/knative/projects/55 ?

**Comment by Cali0707** [comment]
Hey @Leo6Leo can we close this now that the three sub tasks have all been merged?

**Comment by Leo6Leo** [comment]
@Cali0707 Yes this can be closed. I don't have the close access as this is created by @pierDipi 

/close
