### ISSUE TITLE
New Event Filtering: Benchmark Java Implementation of "Any" filter

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3235]
**Problem**
To move New Event Filtering into beta, we should benchmark the "Any" SubscriptionsAPI filter.

To add a benchmark for a new type of filter, add a file to [this folder](https://github.com/knative-extensions/eventing-kafka-broker/tree/main/data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter) for the filter type, and then follow the pattern in https://github.com/knative-extensions/eventing-kafka-broker/pull/3247/files#diff-b300a22e800560bd785d1c686237dbd3bc39979e85ef6699adbbbec58e2101ca. Specifically, when making a new benchmark, you need to extend the `FilterBenchmark` class and override the `createEvent` and `createFilter` functions to create the desired event and filter to benchmark.

**Exit Criteria**
Benchmarks measuring performance of the "Any" filter with combinations of all of the other types of SubscriptionsAPI filters

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 2

**Additional context (optional)**
- https://github.com/knative/eventing/issues/5204
- https://github.com/knative/eventing/issues/7112
- https://github.com/knative-extensions/eventing-kafka-broker/pull/3247

**Comment by Cali0707** [comment]
Note this is not ready to work until after #3233 is finished

**Comment by TunrayoIlawole** [comment]
Hi @Cali0707, I would love to work on this. Can you please assign it to me?

**Comment by TunrayoIlawole** [comment]
Hi @Cali0707, to implement the benchmark for the Any filter, I would need to update the AnyFilter class under [this folder](https://github.com/knative-extensions/eventing-kafka-broker/tree/main/data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter/subscriptionsapi). Is this correct?

**Comment by Cali0707** [comment]
No, you should add a new file to https://github.com/knative-extensions/eventing-kafka-broker/tree/main/data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter and then implement the benchmarks in there as shown in the reference PR [here](https://github.com/knative-extensions/eventing-kafka-broker/pull/3247)

**Comment by TunrayoIlawole** [comment]
Got it, thank you

**Comment by TunrayoIlawole** [comment]
Hi @Cali0707, just want to let you know that I am still working on this. I was having some trouble setting up the development environment, but I've been able to do that and I've been going through the code trying to understand it. I know the AnyFilter expects a Set of filters. Can you please help with an explanation of what those filters are supposed to be?

**Comment by Cali0707** [comment]
@TunrayoIlawole the documentation for these filters can be found here: https://knative.dev/docs/eventing/experimental-features/new-trigger-filters/

In terms of which filters to use for the Any filter benchmarks, I would recommend using the same ones as we are using in eventing core. You can find those here: https://github.com/knative/eventing/pull/7195

Let me know if you have any other questions!
