### ISSUE TITLE
New Event Filtering: Benchmark Java Implementation of "All" filter

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3236]
**Problem**
To move New Event Filtering into beta, we should benchmark the "All" SubscriptionsAPI filter implementation.

To add a benchmark for a new type of filter, add a file to [this folder](https://github.com/knative-extensions/eventing-kafka-broker/tree/main/data-plane/benchmarks/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/filter) for the filter type, and then follow the pattern in https://github.com/knative-extensions/eventing-kafka-broker/pull/3247/files#diff-b300a22e800560bd785d1c686237dbd3bc39979e85ef6699adbbbec58e2101ca. Specifically, when making a new benchmark, you need to extend the `FilterBenchmark` class and override the `createEvent` and `createFilter` functions to create the desired event and filter to benchmark.

**Exit Criteria**
Benchmarks measuring performance of the "All" filter with combinations of all of the other types of SubscriptionsAPI filters

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 2

**Additional context (optional)**
- https://github.com/knative/eventing/issues/5204
- https://github.com/knative/eventing/issues/7113
- https://github.com/knative-extensions/eventing-kafka-broker/pull/3247

**Comment by Cali0707** [comment]
Note this is not ready to work until after https://github.com/knative-sandbox/eventing-kafka-broker/issues/3233 is finished

**Comment by AllMight2099** [comment]
Hi there!
I'm Nishanth, can I take this issue up?

**Comment by Cali0707** [comment]
Hi @AllMight2099! 

Feel free to give this issue a go, let me know if you have any questions as you work on it
/assign @AllMight2099

**Comment by AllMight2099** [comment]
Hi @Cali0707 
Sorry about the delay, There were a few things that I had to take care of so I became a little sidetracked, I'll put in an update later today. I think I've understood everything, but will ping you if I get stuck or if I have any questions

**Comment by Cali0707** [comment]
@AllMight2099 no worries at all! Just let me know if I can be of any assistance :)
