### ISSUE TITLE
Question: Recommended way to disable an entire source

### ISSUE THREAD

**Issue by DavidR91** [knative-extensions/eventing-kafka-broker#3277]
### Scenario
We are switching between a live and a standby cluster, where we want the standby to no longer be pulling events off of Kafka - but _ideally_ we don't want to delete every broker / every trigger each time this switch happens

### Question
Is there a recommended way to drive a setup where an entire source may need to be disabled or disconnected without causing too much 'churn'? (And ideally while allowing any events already in the system to safely drain and complete)

### Additional Info
We're using a Kafka source, and then a number of brokers (10-20) and then per broker we have a number of Triggers (5-10). Deletion/recreation of these triggers etc. each time we switch live and standby would be very awkward (and probably error prone)

**Comment by Cali0707** [comment]
@DavidR91 just to make sure we are on the same page here: when speaking of a live and a standby cluster do you mean a live and a standby Kafka cluster or a live and a standby k8s/knative cluster?

/triage needs-user-input
