### ISSUE TITLE
support using pvc to store broker/trigger contract

### ISSUE THREAD

**Issue by xinglsh6937** [knative-extensions/eventing-kafka-broker#3281]
**Problem**

kafka-broker-controller use configmap `kafka-broker-brokers-triggers` to store broker and trigger configs, but configmap has a storage size limit of 1M, which means that too many Triggers and Brokers cannot be created.

Using pvc instead of configmap may be better, please consider it

**Comment by pierDipi** [comment]
Thanks for reporting, this scalability limitation will be solved by the issues under this project https://github.com/orgs/knative-extensions/projects/11 while also enabling us to implement autoscaling on a per trigger basis (for more info refer to the design documentation https://docs.google.com/document/d/13tKTi5a_cVPj4BDZ-4IFvPXV3Woo6EF5wgegikeWFto/edit#heading=h.n8a530nnrb).

Once the project is completed, it will store configurations in multiple ConfigMaps: one per dispatcher pod (to store pod-specific triggers) and a single one for the receiver to store all brokers configurations (this feature is currently implemented for KafkaSource, so you can try it on KafkaSource and perhaps provide feedback on whether it will solve your issue).

We can definitely use your help in case there is interest in contributing to such project, we can provide guidance and help in getting started.
