### ISSUE TITLE
Add the instruction on how to run single rekt test

### ISSUE THREAD

**Issue by Leo6Leo** [knative-extensions/eventing-kafka-broker#3297]
Sharing some tricks on how to debug rekt based e2e test:
 ```
SYSTEM_NAMESPACE=knative-eventing go test -v -tags=e2e -count=1 -run <The test name that you would like to run>  -parallel=12 -timeout=30m ./test/rekt
```

Take one of your failed test as an example, 
```
 SYSTEM_NAMESPACE=knative-eventing go test -v -tags=e2e -count=1 -run TestEventTransformationForTrigger  -parallel=12 -timeout=30m ./test/e2e_new/
```

This command allows you to run **single** rekt test. You don't have to run all the rekt test and wait for hours for them to be finished.

_Originally posted by @Leo6Leo in https://github.com/knative-extensions/eventing-kafka-broker/issues/3252#issuecomment-1680975774_
            

When you are running kafka broker related test, you may need to specify the broker class

```
 SYSTEM_NAMESPACE=knative-eventing BROKER_CLASS=Kafka go test -v -tags=e2e -count=1 -run TestBrokerTLSCARotation  -parallel=12 -timeout=30m ./test/e2e_new
```

# Description
This ticket is aiming to update DEVELOPMENT.md, to tell the developers what command they can use to run single rekt test. Please also add the explanation for each parameter.

**Comment by rajibmitra** [comment]
I can take this up @Leo6Leo

**Comment by Leo6Leo** [comment]
Hey @rajibmitra, any updates on this issue?

**Comment by Leo6Leo** [comment]
Hello @rajibmitra are you still working on this ticket? If not, we will be assigning this task to other contributors.
