### ISSUE TITLE
Add Spotless Script to hack/run.sh

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3331]
**Problem**
Currently, spotless is run when someone runs `./hack/update-codegen.sh`, or if they know how to manually use spotless itself. We should abstract that away from contributors and allow them to run `./hack/run.sh format-java` and have it format all the java code for them.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Contributors

**Exit Criteria**
Running `./hack/run.sh format-java` formats all the java code.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 1

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by MeenuyD** [comment]
Hello @Cali0707 I would like to work on this issue can you please guide me on how to get started

**Comment by Cali0707** [comment]
@MeenuyD thanks for picking this up! In general, the pattern for adding a command to `./hack/run.sh` is to add the command into https://github.com/knative-extensions/eventing-kafka-broker/blob/main/hack/run.sh, and then in the big set of if statements there, run whatever needs to be run (either calling a new script or running a few bash commands). Here, you would want to run `${ROOT_DIR}/mvnw spotless:apply`.
/assign @MeenuyD

**Comment by Cali0707** [comment]
Completed by #3333
