### ISSUE TITLE
Receiver verticle should use a `File` object for TLS secrets instead of raw strings

### ISSUE THREAD

**Issue by pierDipi** [knative-extensions/eventing-kafka-broker#3368]
**Describe the bug**

Instead of keeping a string as the secrets file path, we should keep a `File` object

https://github.com/knative-extensions/eventing-kafka-broker/blob/1ddc8235e12ed786802a6b6f30e587c8cd9c4220/data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java#L77-L79

so that we don't need to create a File object every time:

- https://github.com/knative-extensions/eventing-kafka-broker/blob/1ddc8235e12ed786802a6b6f30e587c8cd9c4220/data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java#L238-L239
- https://github.com/knative-extensions/eventing-kafka-broker/blob/1ddc8235e12ed786802a6b6f30e587c8cd9c4220/data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java#L179
- https://github.com/knative-extensions/eventing-kafka-broker/blob/1ddc8235e12ed786802a6b6f30e587c8cd9c4220/data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java#L133-L138

 **Knative release version**

`main`, `release-1.11`

 **Additional context**

/kind cleanup
/kind performance

**Comment by Cali0707** [comment]
@pierDipi is this resolved now that #3371 is merged?

**Comment by pierDipi** [comment]
Yes, thanks!
