### ISSUE TITLE
Eventing TLS: E2E tests for Channel TLS key pair rotation

### ISSUE THREAD

**Issue by Leo6Leo** [knative-extensions/eventing-kafka-broker#3374]
**Problem**
We should have rekt-based E2E tests that tests TLS key pairs rotation for channel.
- Part of #3221 

We should make use of:
- https://github.com/knative-extensions/reconciler-test/pull/548
- https://github.com/knative-extensions/reconciler-test/pull/549

Each test flow would be:

Install target resources
- rotate certs (https://github.com/knative-extensions/reconciler-test/pull/549)
- verify new rotated certs are used (https://github.com/knative-extensions/reconciler-test/pull/548)

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1
**Additional context (optional)**
- related to https://github.com/knative/eventing/issues/7039

For Channel tests, this issue depends on:
- https://github.com/knative-extensions/eventing-kafka-broker/issues/3188

**Comment by Cali0707** [comment]
@Leo6Leo while debugging #3252 @pierDipi and I realized that you will need to expose a different port (likely 443) on the channel service for the prober to work
