### ISSUE TITLE
Optimize Kafka cluster connections

### ISSUE THREAD

**Issue by pierDipi** [knative-extensions/eventing-kafka-broker#3397]
**Problem**

In our controllers, we often re-create Kafka cluster connections, the original reason was this issue https://github.com/IBM/sarama/issues/2060 . Now, it's fixed we need to re-review our Kafka cluster interactions in the control plane (for all resources) and see if we can optimize them by reducing the number of TCP connections created.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
`*`

**Exit Criteria**

Lower number of Kafka connections for a single resource reconciliation

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
7

**Additional context (optional)**

/kind performance

**Comment by pierDipi** [comment]
For monitoring and viewing tcp connections for manual testing we could try to use https://www.inspektor-gadget.io/docs/v0.20.0/gadgets/top/tcp/

**Comment by Cali0707** [comment]
Hey @pierDipi for this issue, are you picturing something like a connection pool now that the connections can re-authenticate without being re-created?

/assign

**Comment by pierDipi** [comment]
Let's keep in mind that connection pools and caches are very prone to security issues, so let's have a design that reduces the risk of security issues without over-optimizing too early

**Comment by Cali0707** [comment]
> Let's keep in mind that connection pools and caches are very prone to security issues, so let's have a design that reduces the risk of security issues without over-optimizing too early

Do you have some other ideas? My initial really simple idea was to just create one admin client per Reconciler struct that needs one, but I wasn't sure if that would make too many connections overall. WDYT @pierDipi ?
