### ISSUE TITLE
ConsumerGroups are stuck in finalization when something is wrong with Kafka configuration

### ISSUE THREAD

**Issue by aliok** [knative-extensions/eventing-kafka-broker#3408]
**Describe the bug**
ConsumerGroups are stuck in finalization when something is wrong with Kafka configuration.

2 cases:
- failed to initialize consumer group offset: cannot obtain Kafka cluster admin, kafka: client has run out of available brokers to talk to: dial tcp: address Tryserver: missing port in address
- failed to initialize consumer group offset: failed to create Admin client config: [protocol SASL_SSL] failed to parse CA certificates (key: ca.crt)

More information:
- The namespaces are deleted for the resources, so we don't have any Events (they're already gone)

 **Expected behavior**
Finalizer should really give up.

 **To Reproduce**
I don't have a reproducer right now.

 **Knative release version**
1.9 or 1.10 not sure

 **Additional context**

https://gist.github.com/aliok/fdbf6aa130b9cf2a25ce65923d3630d5 has the full YAML for both resources.

**Comment by aliok** [comment]
cc @pierDipi

**Comment by Cali0707** [comment]
@pierDipi maybe this is related to the KafkaSource cleanup issues we've been seeing?
