### ISSUE TITLE
Port the refactored new events filters tests from eventing core

### ISSUE THREAD

**Issue by Leo6Leo** [knative-extensions/eventing-kafka-broker#3449]
**Problem**
Currently, the new filter tests need to be manually ported one at a time whenever a new test is made. With the recent refactor, we can simply import the whole test suite. We should refactor our tests to do this.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Knative Developers

**Exit Criteria**
The new events filters tests are run with the newly refactored test suite.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 1 day.

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by Cali0707** [comment]
This was completed a while ago, closing
