### ISSUE TITLE
How to manage the kafka source controllers

### ISSUE THREAD

**Issue by ninoamine** [knative-extensions/eventing-kafka-broker#3470]
**Describe the bug**
For some internal issues we actualy using knative eventing 1.3.2 using the operator to install an with activating the kafka controller and we also installed the https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.3.2/eventing-kafka-broker.yaml but we found out that now we have two cosumers groupe used by the kafkasource. So to resolve that we disabled the kafka controller from the knative eventing operator and run the post install.

But now when we create a kafkasource it does not create a deployment and it is managed by the controlle so we are going some perf issues. Is it possible to keep the same behavior of creating a deployement every time we create a kafkasource without having the two consumer groupe issue

 **Expected behavior**
kakasource create a deployment
one consumer groupe for the kafkasource

 **Knative release version**
v1.3.2

**Comment by pierDipi** [comment]
Hi @ninoamine, no, that's not possible anymore, can you please share what performance issues are you running into?

**Comment by ninoamine** [comment]
Hello @pierDipi, now that the kafka-source-dispatche who manages the consumer groupes, we hava lags and it takes a lot o time to consume a new message

**Comment by pierDipi** [comment]
On previous versions you can scale up the kafka-source-dispatcher deployment
```
kubectl scale deployment -n knative-eventing kafka-source-dispatcher --replicas=3
```
