### ISSUE TITLE
Improve error messages throughout EKB

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3487]
**Problem**
In the Knative End User Success Stories talk at KubeCon, we heard that sometimes users will look through the code to figure out what an error message meant, as our error messages don't always give a clear idea of what went wrong, whether the user can fix it, and how to fix it. https://youtu.be/-DN7LQCn7aU?si=-XgsjotxfDkuz8-e&t=730

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Administrators
Developers

**Exit Criteria**
Error messages in logs and CR statuses are actionable

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 5-7

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by pierDipi** [comment]
@Cali0707 can we be specific on which ones are improvable ?

**Comment by Cali0707** [comment]
> @Cali0707 can we be specific on which ones are improvable ?

I think part of the scope of this would be to investigate that since it wasn't fully clear to me when I watched the talk. However, I believe that especially places where we wrap/return underlying library errors would be where I would look first to improve the errors
