### ISSUE TITLE
Request for Assistance with Kafka Client Connections in Kafka Broker Dispatcher

### ISSUE THREAD

**Issue by lamluongbinh** [knative-extensions/eventing-kafka-broker#3500]
Hi knative team,

I am reaching out to seek assistance with an issue related to the number of connections that our Kafka Broker Dispatcher **kafka-broker-dispatcher** is currently opening.

Upon investigation, I discovered that for a single pod of the dispatcher, approximately 200 connections are being opened. This has raised concerns about the scalability and efficiency of our Kafka client connections.

I would appreciate it if you could provide guidance or assistance on how we can control and optimize the number of Kafka client connections established by the **Kafka Broker Dispatcher**. Are there specific configuration options or best practices that we should be aware of to manage and limit the number of connections per pod?

I am using release-1.10.

Thanks team

**Comment by pierDipi** [comment]
Hi, thanks for opening an issue, can you please share your setup, how many nodes your Kafka clusters have ? how many Knative brokers with class Kafka as well as how many triggers you have?
