### ISSUE TITLE
kafka source dispatcher stuck in a offset when message is too large

### ISSUE THREAD

**Issue by ninoamine** [knative-extensions/eventing-kafka-broker#3501]
**Describe the bug**
For some internal issues we actualy using knative eventing 1.3.2 using the operator to install an with activating the kafka controller and we also installed the https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.3.2/eventing-kafka-broker.yaml but we found out that now we have two cosumers groupe used by the kafkasource. So to resolve that we disabled the kafka controller from the knative eventing operator and run the post install.

But now the kafka source dispatcher is stuck in a offset when message is too large

 **Expected behavior**
clear error message or something

**Comment by pierDipi** [comment]
If the message is too large you can change the consumers configurations for KafkaSource in the `config-kafka-source-data-plane` ConfigMap

https://github.com/knative-extensions/eventing-kafka-broker/blob/7b581b7807df14b27b7100293706da8269c04c45/data-plane/config/source/100-config-kafka-source-data-plane.yaml#L93
