### ISSUE TITLE
Remove the unsupposrted unsupported channel implementations from the doc

### ISSUE THREAD

**Issue by Leo6Leo** [knative-extensions/eventing-kafka-broker#3525]
**Problem**
Currently, as discussed [here](https://github.com/knative-extensions/eventing-kafka-broker/pull/3219#discussion_r1375881159), `consolidated KafkaChannel` and `distributed KafkaChannel` are not supported by Knative anymore. Therefore, we need to update the documentations to reflect this change. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Developer

**Exit Criteria**
Have clear indicate that `consolidated KafkaChannel` and `distributed KafkaChannel` are not supported by Knative anymore, and have the link to the latest knative release. Make sure all the old links are removed.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**

> Let's update:
> * point to the last release
> * say that these _other_ channels are NOT supported 
> 
> OR even better: update the doc, and completely remove any mention of those unsupported other channel implementations. Makes sense?
> 
> _Originally posted by @matzew in https://github.com/knative-extensions/eventing-kafka-broker/pull/3219#discussion_r1420032521_

**Comment by Cali0707** [comment]
Hey @Leo6Leo could you clarify the ask/scope of this issue?
