### ISSUE TITLE
Fix the flaky FileWatcher unit test in the data plane

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3536]
**Describe the bug**
With the bump to JDK 21, the `FileWatcherTest` test fails in Github Actions but passes in Prow (and often locally). 

 **Expected behavior**
The test should consistently pass

 **To Reproduce**
Run the `FileWatcherTest` tests in Github Actions

 **Knative release version**
main

 **Additional context**

The error logs from the tests are:
```
[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    FileWatcherTest.testFileModification:64 » ConditionTimeout Condition dev.knative.eventing.kafka.broker.core.file.FileWatcherTest$$Lambda/0x00007f011417fa10 was not fulfilled within 10 seconds.
```

**Comment by Cali0707** [comment]
cc @Leo6Leo - iirc you implemented this test originally, maybe you have thoughts on how to fix it?

**Comment by Leo6Leo** [comment]
The dependency upgrade tests are passing on GitHub as shown [here](https://github.com/knative-extensions/eventing-kafka-broker/actions/workflows/knative-java-test.yaml?query=branch%3Amain+event%3Apush), so closing this issue.

/close
