### ISSUE TITLE
Add deploy-control-plane command to `hack/run.sh`

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3552]
**Problem**
Currently, if you are iterating on the ekb control plane, you need to rebuild both the data plane and control plane. To improve developer productivity, it should be possible to rebuild the control plane only.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Knative developers

**Exit Criteria**
Running `./hack/run.sh deploy-control-plane` rebuilds and deploys the control plane only, without building the data plane.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 2 days

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by pierDipi** [comment]
/triage accepted

If you could give more pointers this could be a good first-good-issues

**Comment by Cali0707** [comment]
To approach this issue, a function similar to https://github.com/knative-extensions/eventing-kafka-broker/blob/0ed108c468be215c796a1b9faff20ff12aca0d6c/test/e2e-common.sh#L128-L147 should be created in the same file, except it should only remove/call setup functions for the control plane and monitoring artifacts.

Then, `./hack/run.sh` should be updated to have a new option for `deploy-control-plane` by adding the option to the list here https://github.com/knative-extensions/eventing-kafka-broker/blob/0ed108c468be215c796a1b9faff20ff12aca0d6c/hack/run.sh#L9-L42

And finally, the option should be added to the large if else block lower in `./hack/run.sh`, where `./test/e2e-common.sh` should be sourced and the new function you created called.

**Comment by NeerajNagure** [comment]
Can I work on this issue if its not been resolved?
