### ISSUE TITLE
Question: Does Receiver and Dispatcher support multiple architectures?

### ISSUE THREAD

**Issue by valen-mascarenhas14** [knative-extensions/eventing-kafka-broker#3652]
We have recently submitted a pull request (PR #3644) aiming to extend the support for the ppc64le architecture in the Jib Maven build task for the dispatcher and receiver images within the `eventing-kafka-broker` repository.

To ensure a comprehensive approach and successful integration, I would like to raise this issue to gather insights and clarify the necessary steps regarding the manifest creation for ppc64le architecture.

**Key Questions:**

- Which is the CI tool used to uploaded both the images to GCR  ?
- I can find the AMD64, ARM64 and s390x manifests [here](https://console.cloud.google.com/gcr/images/knative-releases/global/knative-kafka-broker-receiver@sha256:c01ff5d74a38d4d28d46f906ce38b204ef5c9812f7c545d9e3c78cee254c8591/details?tab=pull). What additional steps or considerations are required to include ppc64le architecture manifests for the dispatcher and receiver images? Will the ppc64le architecture be added to the manifest after in the next `eventing-kafka-broker` release ?
- Are there any specific configurations or adjustments needed in the existing CI tooling for uploading images to GCR, considering the expanded architecture support?

Thanks !

**Comment by valen-mascarenhas14** [comment]
@haubenr Would you be able to provide some guidance on this ?

**Comment by haubenr** [comment]
I've moved on to a new job role a long time ago, so I'm no longer involved with knative in any capacity. You may want to get in touch in with @dilipgb - he might have some insights.

**Comment by dilipgb** [comment]
@haubenr thanks for bringing it to my notice.

@valen-mascarenhas14 Receiver and Dispatcher is built as part of the test execution. We use local images that built as part of test setup and we store the images in local repository we use for testing. 

Here is the release pipeline in prow you can refer for publishing to gcr.io you are referring: https://github.com/knative/infra/blob/main/prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml

The PR for adding ppc64le to pom.xml was merged 16 hours ago but release job ran 21 hours ago. I think next run it may pickup the ppc arch as well.

**Comment by ghatwala** [comment]
thanks @dilipgb for above details  , hopefully the next prow job will help add `ppc64le` arch manifests to both images at gcr.io just like `s390x`

**Comment by dilipgb** [comment]
@ghatwala I verified the crontab and its configured to run every tuesday. FYI... Please find the reference. https://github.com/knative/infra/blob/main/prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml#L75C9-L75C19
