### ISSUE TITLE
[control-plane]: Use filtered informer to watch OIDC service accounts

### ISSUE THREAD

**Issue by creydr** [knative-extensions/eventing-kafka-broker#3655]
Currently we're watching all service accounts in the cluster for changes and reenque the objects which have an OIDC service account assigned if something changes:

https://github.com/knative-extensions/eventing-kafka-broker/blob/45c65c8b780a312de497e560e5afccb2644feca9/control-plane/pkg/reconciler/trigger/controller.go#L145-L149

and 

https://github.com/knative-extensions/eventing-kafka-broker/blob/45c65c8b780a312de497e560e5afccb2644feca9/control-plane/pkg/reconciler/trigger/namespaced_controller.go#L141-L144

Instead we should use a filtered service account informer as done in https://github.com/knative/eventing/issues/7341

**Additional information:**
* requires #3521 done first
* requires #3658 
* In https://github.com/knative/eventing/pull/7527 we did this in eventing-core

**Comment by karkabbage** [comment]
Hi @creydr , thanks for checking in!
From what I understand, I'll be following mostly from #[7527](https://github.com/knative/eventing/pull/7527/files#diff-f3f6de1fc27913dd0c661e6198db2368a1092d9e3125292d7798ad6d991452b3) to change similar files for the trigger controllers.

**Comment by creydr** [comment]
> Hi @creydr , thanks for checking in! From what I understand, I'll be following mostly from #[7527](https://github.com/knative/eventing/pull/7527/files#diff-f3f6de1fc27913dd0c661e6198db2368a1092d9e3125292d7798ad6d991452b3) to change similar files for the trigger controllers.

Hello @karkabbage,
yes. It will be similar to what was done in https://github.com/knative/eventing/pull/7527
