### ISSUE TITLE
disabling Keda scale doesn't take effect

### ISSUE THREAD

**Issue by converge** [knative-extensions/eventing-kafka-broker#3669]
**Describe the bug**
[ok] Setting configmap config-kafka-features / `controller.autoscaler` from disabled to enabled takes effect.
[failing] setting configmap config-kafka-features / `controller.autoscaler` from enabled to disabled doesn't takes effect.

 **Expected behavior**
Setting configmap config-kafka-features / `controller.autoscaler` from enabled to disabled should delete related scale resources created when the flag is switched from `disabled` to `enabled`, it will include:

Keda: Scaled Object, Authentication Trigger
Others: ConsumerGroups?

 **To Reproduce**
1. configmap config-kafka-features / `controller.autoscaler` from disabled to enabled takes effect.
2. setting configmap config-kafka-features / `controller.autoscaler` from enabled to disabled doesn't takes effect.
3. kubectl get so -A

the expected behaviour is that the Keda objects would be deleted.

 **Knative release version**
1.13 (eventing and serving)

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by Cali0707** [comment]
@converge - we should not delete consumergroups when the flag is changed, but it should delete the KEDA stuff. Would you be interested in working on a fix for this?

/triage-accepted
/area control-plane

**Comment by converge** [comment]
> @converge - we should not delete consumergroups when the flag is changed, but it should delete the KEDA stuff. Would you be interested in working on a fix for this?
> 
> /triage-accepted /area control-plane

Yes, I'll give it a try on my spare time.
