### ISSUE TITLE
Allow configuring KEDA scaling options

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3672]
**Problem**
Currently, we hardcode all of the KEDA scaling options. Some users may want to configure these themselves. We should support users setting these options. I imagine we can follow a similar approach to the broker-kafka-config configmaps. Essentially, we would have a configmap that includes the keys with the KEDA config values. We could support one global one in the knative-eventing namespace, as well as a per-(source/broker/trigger/channel/subscription) override (order of precedence would be trigger, then broker, then global).

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Administrators, Developers

**Exit Criteria**
All the KEDA options are configurable by users through configmaps

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 2

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by Cali0707** [comment]
Thoughts on this approach @pierDipi ?

**Comment by pierDipi** [comment]
Isn't this possible via annotations here https://github.com/knative-extensions/eventing-kafka-broker/blob/main/control-plane/pkg/autoscaler/autoscaler_api.go ?

**Comment by Cali0707** [comment]
> Isn't this possible via annotations here https://github.com/knative-extensions/eventing-kafka-broker/blob/main/control-plane/pkg/autoscaler/autoscaler_api.go ?

Yes you are correct, sorry for missing that! I was getting confused by: https://github.com/knative-extensions/eventing-kafka-broker/blob/02be94e0e58f1755cce26af7a8d0ab8b5e57d8d3/control-plane/pkg/reconciler/source/source.go#L208-L209
