### ISSUE TITLE
[unit tests] reconciliation removal of keda objects

### ISSUE THREAD

**Issue by converge** [knative-extensions/eventing-kafka-broker#3701]
**Problem**
this PR https://github.com/knative-extensions/eventing-kafka-broker/pull/3676 is missing unit tests. I would like to create them on a separated PR.

**Comment by Cali0707** [comment]
/triage accepted
/assign @converge 

Thanks for volunteering to work on this on slack @converge , feel free to unassign if you change your mind!

**Comment by Cali0707** [comment]
I believe this is resolved now, feel free to re-open if for some reason it isn't
/close
