### ISSUE TITLE
Add Sacura Tests to KEDA test job

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3711]
**Problem**
Currently we are not running the Sacura test in the KEDA test job. To catch performance issues, we should enable them.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
Sacura tests run in the KEDA job

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 1

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by NeerajNagure** [comment]
@Cali0707 I would like to work on this. From what I could understand is that I have to put a command in `test/keda-reconciler-tests.sh` which is similar to that of  [https://github.com/knative-extensions/eventing-kafka-broker/blob/eb1ebaeb480cd08b8278c1aadf690bc9e1690253/hack/run.sh#L78](url) to run sacura test in keda job.Am I right?

**Comment by Cali0707** [comment]
Hey @NeerajNagure , yes it would be similar to what you saw in `hack/run.sh/L#78`. However, I would actually recommend looking at https://github.com/knative-extensions/eventing-kafka-broker/blob/315e260db7a27c0e899d6b2a34eacc8e5a06abf3/test/reconciler-tests.sh#L73-L75 and then adding that to the keda test job
