### ISSUE TITLE
tracing: kafka-broker-dispatcher: add trigger's name and uuid to kafka-broker-dispatcher's trace tags

### ISSUE THREAD

**Issue by eddy-oum** [knative-extensions/eventing-kafka-broker#3720]
**Problem**
A short explanation of the problem, including relevant restrictions.
![image](https://github.com/knative-extensions/eventing-kafka-broker/assets/120997314/075d861a-6926-4790-8e71-c293862c22e5)

The 'post' operation trace generated by kafka-broker-dispatcher currently only includes the 'http.url' in its tags.
Distinguishing between traces becomes challenging when multiple triggers with different filters share the same subscriber URL.
To address this issue, I propose adding the trigger's name and UUID to the trace tags. 

I believe this is achievable since RecordDispatcherImpl class has access to the trigger's name and UUID through ```consumerVerticleContext.getEgress().getReference()```.
This information can be added to the span during creation or when invoking ```span.finish()``` or ```.fail()```.
However, I acknowledge that this is a speculative suggestion.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Event consumer (developer)

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.
trace tags contains trigger uuid and trigger name tags.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by Cali0707** [comment]
/triage accepted
@eddy-oum would you be interested in contributing a fix for this? I would be happy to help you get started

**Comment by eddy-oum** [comment]
@Cali0707 
sure, i will be glad to contribute.

**Comment by eddy-oum** [comment]
@Cali0707

I looked in to the code and think I can include egress ref's to the tags by using a diffrent tag extractor for the reciever.
But this means I have to add ```egressName``` and ```egressUuid``` to the TraceContext(https://github.com/knative-extensions/eventing-kafka-broker/blob/main/data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/kafka/TraceContext.java)

I was wondering if introducing egress related fields to the TraceContext is optimal since
1) the TraceContext class is shared by both producer and the consumer
2) its fields are related to kafka only


```java
// https://github.com/knative-extensions/eventing-kafka-broker/blob/main/data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/tracing/kafka/ConsumerTracer.java
    public class StartedSpan {
        private final S span;

        private StartedSpan(S span) {
            this.span = span;
        }

        public void finish(Context context) {
            // We don't add any new tag to the span here, just stop span timer
            // tracer.sendResponse(context, null, span, null, TagExtractor.empty());

            
            // use a new tag extractor that add egress.name and egress.uuid from trace context.
            tracer.sendResponse(context, null, span, null, EgressTraceTags.TAG_EXTRACTOR);
        }

        public void fail(Context context, Throwable failure) {
            tracer.sendResponse(context, null, span, failure, EgressTraceTags.TAG_EXTRACTOR);
        }
    }
```

**Comment by eddy-oum** [comment]
@Cali0707 
I've submitted a pr.

It appears that we can include tags from various classes, such as StartedSpan::finish / :: fail and TracingSpan::decorateCurrentWithXYZ, etc.

For simplicity, I added decorateCurrentWithEgress to the TracingSpan class. If there are more effective approaches to handle this, feel free to share your thoughts and suggestions. Thanks!
