### ISSUE TITLE
Use new logging package in all e2e test `main` functions

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3753]
**Problem**
In https://github.com/knative-extensions/eventing-kafka-broker/pull/3735 we added a new package which is better at collecting logs, but we aren't calling this everywhere. Specifically, it is only being called in the main function in `test/e2e_new`. We should update the other main functions to set up the logging in a similar way

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
Developers

**Exit Criteria**
All e2e tests successfully collect the logs with the new logging package

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 1

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by Cali0707** [comment]
This will be ready to work on when #3735 merges

**Comment by tico88612** [comment]
Hi @Cali0707, I'm a new open-source contributor.

I want to ensure that `main_test.go` in the `test/e2e.*` folder uses the new logging, right?
If so, could you assign the issue to me? I want to try it out.
