### ISSUE TITLE
[Possible Ignorance] Issue with Events Replaying from 2 weeks back

### ISSUE THREAD

**Issue by nkreiger** [knative-extensions/eventing-kafka-broker#3767]
**Describe the bug**

Everytime the `kafka-broker-dispatcher` restarts, all my triggers spam out, and start pulling in events from what looks like the beginning of the retention time (about 2 weeks). Resulting in an overload.

```
auto.offset.reset=latest
enable.auto.commit=true
```
Both of these values are set, but it seems like, from my limited knowledge of kafka, that it is starting from a much earlier offset when the dispatcher restarts?

 **Expected behavior**

No events are replayed, every consumer starts at the latest offset.

 **To Reproduce**

Delete the `kafka-broker-dispatcher` pod.

My broker is hosted by `Confluent Kafka Cloud`

 **Knative release version**
 
 v1.12.0

 **Additional context**

Happy to provide additional context, but I am not a kafka expert and am looking for some minor assistance to point into the right direction so I can provide a full bug report.

**Comment by nkreiger** [comment]
If you change the broker data plane, is it not enough to restart the controller? Do you have to fully delete and re-create the broker? It seems like that might be true for certain configurations?

I've had trouble with a lot of resources like, triggers, until I fully reset the broker?

**Comment by Cali0707** [comment]
@nkreiger have you tried using https://knative.dev/docs/eventing/brokers/broker-types/kafka-broker/#consumer-offsets-commit-interval?

**Comment by nkreiger** [comment]
Hi @Cali0707 I will investigate, and report back on this!

**Comment by Cali0707** [comment]
> If I create a new trigger, it starts from the beginning of the retention period (1 week).
Is this expected? Should a completely new trigger start from the latest offset? I can see in my confluent kafka dashboard that the offset is going up.

Can you try setting `auto.offset.reset=latest` as well @nkreiger ?

**Comment by nkreiger** [comment]
Hi @Cali0707 this value is also set:

```
~ » k get cm config-kafka-broker-data-plane -n knative-eventing -o yaml | grep auto.offset
    auto.offset.reset=latest
```

It was set when I created the new trigger two nights ago as well.

**Comment by pierDipi** [comment]
> **However**
> 
> If I create a new trigger, it starts from the beginning of the retention period (1 week).
> 
> Is this expected? Should a completely new trigger start from the latest offset? I can see in my confluent kafka dashboard that the offset is going up.

For the latest offset we have a test verifying that previously sent events are not received
https://github.com/knative-extensions/eventing-kafka-broker/blob/551691cda3489753cbee5fa4a95a73c729de73d6/test/rekt/features/trigger_offset_reset.go#L38

This is tested using the default configurations, however, one issue that might occur is when you create a trigger with the same name and namespace of another one previously created, that might have left the consumer group metadata in Kafka (maybe check Confluent UI for this) and in that case, it will  start from whatever is the "latest" offset for that particular existing consumer group is.
This is a bug that will be fixed in the next releases.

**Comment by nkreiger** [comment]
Hmm, interesting @pierDipi thanks for the input, I will take a look at this to see if that is the case. I will check my configurations against your tests as well.

Maybe this is also kicking into affect on the restart as well.

**Comment by nkreiger** [comment]
@pierDipi another QQ, is the kafka broker dispatcher safe to scale up? (multiple pods)

**Comment by joke** [comment]
@nkreiger A similar think happened to me a few weeks ago where old events have been replayed. The problem seems to be caused by an "unclean leader election". [`unclean.leader.election.enable`](https://docs.aws.amazon.com/msk/latest/developerguide/msk-default-configuration.html) is enabled by default on AWS/MSK, which seems a rather questionable choise if you look at the [description](https://kafka.apache.org/documentation/#brokerconfigs_unclean.leader.election.enable). The knative kafka logs reported an [`LogTruncationException`](https://kafka.apache.org/37/javadoc/org/apache/kafka/clients/consumer/LogTruncationException.html) indicating such an unclean leader election had happened.

**Comment by pierDipi** [comment]
> @pierDipi another QQ, is the kafka broker dispatcher safe to scale up? (multiple pods). Feel free just to point me to any docs I may have missed on it.

Yes, you can safely scale it up

**Comment by pierDipi** [comment]
> @nkreiger A similar think happened to me a few weeks ago where old events have been replayed. The problem seems to be caused by an "unclean leader election". [`unclean.leader.election.enable`](https://docs.aws.amazon.com/msk/latest/developerguide/msk-default-configuration.html) is enabled by default on AWS/MSK, which seems a rather questionable choice if you look at the [description](https://kafka.apache.org/documentation/#brokerconfigs_unclean.leader.election.enable). The knative kafka logs reported an [`LogTruncationException`](https://kafka.apache.org/37/javadoc/org/apache/kafka/clients/consumer/LogTruncationException.html) indicating such an unclean leader election had happened.

Thank you! This is a very useful information!

**Comment by nkreiger** [comment]
@joke Thanks for the input -- took a look:

```
unclean.leader.election.enable = false
```

this is disabled by default for me in **Confluent Kafka**. @pierDipi It looks like for me the commit offset was reset to the earliest retention period (7 days), and it started re-consuming all the events. If I see it again, I will grab a log dump.

**Comment by nkreiger** [comment]
Also seeing some other errors @pierDipi . I'm not seeing any access or high traffic either that caused it. Does this happen if a DLQ is not setup?

`
kafka-broker-dispatcher-75bc5bb7f7-m2g7v   0/1     Running   0          29h
kafka-broker-dispatcher-75bc5bb7f7-r6bdh   0/1     Running   0          29h
`

`
Failed to send event to subscriber context={topics=[knative-broker-fianu-dev-default], consumerGroup='knative-trigger-fianu-dev-wiz-containerscan-0', reference=uuid: "7138dea6-def2-46b4-bb8d-c27da10460e0"
namespace: "fianu-dev"
name: "wiz-containerscan-0"
} topic=knative-broker-fianu-dev-default partition=0 offset=27
`

`
dev.knative.eventing.kafka.broker.dispatcher.impl.ResponseFailureException: Received failure response, status code: 500
	at dev.knative.eventing.kafka.broker.dispatcher.impl.http.WebClientCloudEventSender.lambda$send$5(WebClientCloudEventSender.java:201)
	at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
	at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:397)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:384)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:291)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$7(HttpContext.java:507)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.WorkerContext.lambda$run$3(WorkerContext.java:106)
	at io.vertx.core.impl.WorkerContext.lambda$null$1(WorkerContext.java:92)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

`

```
Topology Spread Constraints:  topology.kubernetes.io/zone:ScheduleAnyway when max skew 2 is exceeded for selector app=kafka-broker-dispatcher
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  108s (x32746 over 29h)  kubelet  Readiness probe failed: Get "http://10.1.3.91:9090/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  ```

**Comment by nkreiger** [comment]
Another possibility that could cause it?

"The default.topic.replication.factor value must be less than or equal to the number of Kafka broker instances in your cluster. For example, if you only have one Kafka broker, the default.topic.replication.factor value should not be more than 1."

Not sure what this phrase means in the documentation. Each "broker instance" would be different right? Is it talking about just overall Broker instances applied, or a replication of a single broker instance, and how would one go about replicating that

**Comment by nkreiger** [comment]
I was running a version behind `1.12.0`. I've upgraded everything to the latest -- will continue to monitor. I don't see any replays happening from the upgrade.

**Comment by joke** [comment]
> Another possibility that could cause it?
> 
> "The default.topic.replication.factor value must be less than or equal to the number of Kafka broker instances in your cluster. For example, if you only have one Kafka broker, the default.topic.replication.factor value should not be more than 1."
> 
> Not sure what this phrase means in the documentation. Each "broker instance" would be different right? Is it talking about just overall Broker instances applied, or a replication of a single broker instance, and how would one go about replicating that

The documentation is referring to a Kafka broker/server instances. Not to be confused with the knative kafka broker component.
