### ISSUE TITLE
[flaky] TestBrokerSendsEventsWithOIDCSupport/Broker_send_events_with_OIDC_support/BrokerSendEventWithOIDCTokenToDLS/Assert/broker_with_DLS_deliver_event_to_DLQ 

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3832]
**Describe the bug**
The test
`TestBrokerSendsEventsWithOIDCSupport/Broker_send_events_with_OIDC_support/BrokerSendEventWithOIDCTokenToDLS/Assert/broker_with_DLS_deliver_event_to_DLQ ` has been somewhat flaky in CI, example run here: https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3816/reconciler-tests_eventing-kafka-broker_main/1778778867759058944

 **Expected behavior**
The test is not flaky

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by Cali0707** [comment]
cc @creydr - any ideas?

**Comment by creydr** [comment]
> cc @creydr - any ideas?

Nothing directly. Need to investigate deeper...

**Comment by Cali0707** [comment]
FWIW, I think this got introduced when we moved to triggerv2 and using consumergroups/consumers to reconcile the dispatcher. Seeing similar flakes on the channelv2 PR

**Comment by pierDipi** [comment]
@Cali0707 is this still an issue with the latest updates?
