### ISSUE TITLE
Move KafkaChannel and KafkaSource CRD to v1

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-kafka-broker#3890]
**Problem**
I noticed that we say that the components are GA in the README, but our CRDs are still v1beta1. Does it make sense to think about moving them to v1 now?

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by Cali0707** [comment]
cc @pierDipi @matzew @creydr

**Comment by pierDipi** [comment]
Created separate tasks for:
- https://github.com/knative-extensions/eventing-kafka-broker/issues/3953
- https://github.com/knative-extensions/eventing-kafka-broker/issues/3955
- https://github.com/knative-extensions/eventing-kafka-broker/issues/3956
