### ISSUE TITLE
v1.14.7 `kafka-broker-dispatcher` StatefulSet descriptor is missing `contract-resources` volume definition

### ISSUE THREAD

**Issue by mdwhitley** [knative-extensions/eventing-kafka-broker#3995]
**Describe the bug**
The latest release resources for the [eventing-kafka-broker](https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.14.7/eventing-kafka-broker.yaml), which defines the new StatefulSet for `kafka-broker-dispatcher`, is missing a volume definition for the new `contract-resources` volumeMount. This results in the StatefulSet erroring when applied to a k8 cluster.

This appears to be an issue due to refactor of mounts from triggers to `contract-resources`. The issue is solved by adding a volume for `contract-resources` and pointing back to the old trigger ConfigMap
```
      volumes:
        - name: contract-resources
          configMap:
            name: kafka-broker-brokers-triggers
```

 **Expected behavior**
The `kafka-broker-dispatcher` statefulset should be created successfully and create the desired number of pods.

 **To Reproduce**
Take the release resource and apply to your cluster.

 **Knative release version**
v1.14.7

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by pierDipi** [comment]
cc @Cali0707

**Comment by Cali0707** [comment]
Hey @mdwhitley could you clarify what you mean by 
> the StatefulSet erroring when applied to a k8 cluster.

This will help us understand what issue you are facing. Thanks!

/triage needs-user-input

**Comment by mdwhitley** [comment]
When applied to the cluster the StatefulSet does not become ready:
```
$ k -n knative-eventing get statefulsets                                                                               
NAME                      READY   AGE
kafka-broker-dispatcher   0/2     146m
```

and when you check the resource it failed because the volumeMount references a volume that is undefined:
```
  Warning  FailedCreate  8m29s (x26 over 147m)  statefulset-controller  create Pod kafka-broker-dispatcher-0 in StatefulSet kafka-broker-dispatcher failed error: Pod "kafka-broker-dispatcher-0" is invalid: spec.containers[0].volumeMounts[1].name: Not found: "contract-resources"
  ```

**Comment by Cali0707** [comment]
Was the Kafka controller also applied into the cluster when this happened?

**Comment by mdwhitley** [comment]
Yes. Both [eventing-kafka-broker.yaml](https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.14.7/eventing-kafka-broker.yaml) and [eventing-kafka-controller.yaml](https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.14.7/eventing-kafka-controller.yaml) were applied concurrently to the cluster. All other resources started up fine. 

It is just the issue of trying to reference the undefined volume `contract-resources` under the `kafka-broker-dispatcher`'s volumeMount which causes the problem. Once it is properly defined, everything works fine.

**Comment by Cali0707** [comment]
Okay, the kafka controller is supposed to create and mount that volume on its own, which is why I am asking. Not sure why that isn't occurring in this case. @pierDipi any ideas?

**Comment by pierDipi** [comment]
@mdwhitley can you list the pods running in `knative-eventing`

```
kubectl get pods -n knative-eventing
```

The volume is injected by the `kafka-webhook-eventing` as configured by the `MutatingWebhookConfiguration` `pods.defaulting.webhook.kafka.eventing.knative.dev`

**Comment by mdwhitley** [comment]
Running pods:
```
$ kubectl get pods -n knative-eventing                                                                      
NAME                                          READY   STATUS    RESTARTS   AGE
eventing-controller-8498d8669d-cwjst          1/1     Running   0          14h
eventing-controller-8498d8669d-dhz97          1/1     Running   0          3d19h
eventing-controller-8498d8669d-q2rl2          1/1     Running   0          3d19h
eventing-webhook-6f66bd5668-qnv79             1/1     Running   0          3d18h
eventing-webhook-6f66bd5668-rn8fn             1/1     Running   0          3d19h
kafka-broker-dispatcher-0                     1/1     Running   0          3d19h
kafka-broker-dispatcher-1                     1/1     Running   0          3d18h
kafka-broker-receiver-6686bd55cf-952qg        1/1     Running   0          3d19h
kafka-broker-receiver-6686bd55cf-l59lt        1/1     Running   0          3d19h
kafka-controller-c6566cbc-4mxf9               1/1     Running   0          7h44m
kafka-controller-c6566cbc-l8cvc               1/1     Running   0          3d19h
kafka-controller-c6566cbc-lt4mw               1/1     Running   0          14h
kafka-webhook-eventing-c678b7dc7-6tx8t        1/1     Running   0          3d19h
kafka-webhook-eventing-c678b7dc7-bprsh        1/1     Running   0          3d19h
kafka-webhook-eventing-c678b7dc7-bvxqw        1/1     Running   0          3d19h
```

webhook config:
```
$ kubectl get MutatingWebhookConfiguration pods.defaulting.webhook.kafka.eventing.knative.dev -oyaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"app.kubernetes.io/version":"c7ff0ae5c97c58ca1a904d4acf411b448df90aaf"},"name":"pods.defaulting.webhook.kafka.eventing.knative.dev"},"webhooks":[{"admissionReviewVersions":["v1","v1beta1"],"clientConfig":{"service":{"name":"kafka-webhook-eventing","namespace":"knative-eventing"}},"failurePolicy":"Fail","matchPolicy":"Equivalent","name":"pods.defaulting.webhook.kafka.eventing.knative.dev","namespaceSelector":{"matchLabels":{"kubernetes.io/metadata.name":"knative-eventing"}},"objectSelector":{"matchLabels":{"app.kubernetes.io/kind":"kafka-dispatcher"}},"reinvocationPolicy":"IfNeeded","sideEffects":"None","timeoutSeconds":2}]}
  creationTimestamp: "2022-11-27T02:17:42Z"
  generation: 106
  labels:
    app.kubernetes.io/version: c7ff0ae5c97c58ca1a904d4acf411b448df90aaf
  name: pods.defaulting.webhook.kafka.eventing.knative.dev
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Namespace
    name: knative-eventing
    uid: 9b717c96-1fe9-44c4-9abd-88e0cf6cd62b
  resourceVersion: "5739807244"
  uid: 2326fdbd-ea32-4279-91a3-51d563e1f7ca
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {redacted}
    service:
      name: kafka-webhook-eventing
      namespace: knative-eventing
      path: /pods-defaulting
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: pods.defaulting.webhook.kafka.eventing.knative.dev
  namespaceSelector:
    matchExpressions:
    - key: webhooks.knative.dev/exclude
      operator: DoesNotExist
    matchLabels:
      kubernetes.io/metadata.name: knative-eventing
  objectSelector:
    matchLabels:
      app.kubernetes.io/kind: kafka-dispatcher
  reinvocationPolicy: IfNeeded
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - pods/status
    scope: '*'
  sideEffects: None
  timeoutSeconds: 2
  ```

fwiw the webhook config looks the same with or without `authentication-oidc` enabled in `config-features` ConfigMap.

**Comment by treyhyde** [comment]
FWIW, I see the same thing.    I try to go to upgrade from 1.13 -> 1.14 every few weeks but keep hitting cases like this and always revert back to 1.13

Thinking it might be a race condition with order in which the manifests are applied, I made sure controller was running and deleted the statefulsets, when re-applied they still are missing `contract-resources`.

**Comment by pierDipi** [comment]
@mdwhitley I see from the list https://github.com/knative-extensions/eventing-kafka-broker/issues/3995#issuecomment-2245254517 that they are running, so is the issue only when applying resources in the first 100 seconds?

```
kafka-broker-dispatcher-0                     1/1     Running   0          3d19h
kafka-broker-dispatcher-1                     1/1     Running   0          3d18h
```

**Comment by pierDipi** [comment]
I've also tried locally with:
```
kubectl apply -f https://github.com/knative/eventing/releases/download/knative-v1.14.5/eventing-crds.yaml
kubectl apply -f https://github.com/knative/eventing/releases/download/knative-v1.14.5/eventing-core.yaml
kubectl apply --filename https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.14.7/eventing-kafka-controller.yaml
kubectl apply --filename https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.14.7/eventing-kafka-broker.yaml
./test/kafka/kafka_setup.sh
```

```
kubectl apply -f ../kafka-broker-example.yaml
```

```
k get brokers.eventing.knative.dev -A
NAMESPACE   NAME   URL                                                                         AGE   READY   REASON
default     br     http://kafka-broker-ingress.knative-eventing.svc.cluster.local/default/br   10s   True    
```

**Comment by pierDipi** [comment]
@mdwhitley the changes above

> This appears to be an issue due to refactor of mounts from triggers to `contract-resources`. The issue is solved by adding a volume for `contract-resources` and pointing back to the old trigger ConfigMap
```
      volumes:
        - name: contract-resources
          configMap:
            name: kafka-broker-brokers-triggers
```

are not correct and shouldn't not be applied as it will give the false impression that the system is working but it's not

**Comment by mdwhitley** [comment]
What would you expect not to be working? We have that change applied to our dev cluster since this issue was opened and events are still triggered and routed as expected.

**Comment by pierDipi** [comment]
Because the new architecture is based on having one configmap per pod to hold pod-assigned consumers as described in #1537, by having the (single) ConfigMap that was used in the previous version, new triggers will not be configured correctly

**Comment by treyhyde** [comment]
I think my issue may have been from kustomize patches that change he `replica` number based on the configuration of the cluster.    In this new setup, if this is done external to this new controller born autoscaler, it appears to break hard.

**Comment by stanislav-pimenov** [comment]
Hi guys.

We are having the same issue in our cluster

I'm fully on the same page as @pierDipi. Since adding hardcoded volume to the Statful is not the way out. And will cause issue as soon as 2nd instance of kafka-source-dispatcher is up and try running.

@pierDipi Am I right that you've done the fix? in #4027 ? Is it going to be released soon?

**Comment by yuehaii** [comment]
> Because the new architecture is based on having one configmap per pod to hold pod-assigned consumers as described in #1537, by having the (single) ConfigMap that was used in the previous version, new triggers will not be configured correctly

when this fix can be released? I met same issue today with knative-kafka-broker-dispatcher-loom:v1.15.2

**Comment by stanislav-pimenov** [comment]
tested on the newly released 1.15.4, problem still exists
`create Pod kafka-source-dispatcher-0 in StatefulSet kafka-source-dispatcher failed error: Pod "kafka-source-dispatcher-0" is invalid: spec.containers[0].volumeMounts[1].name: Not found: "contract-resources"`

**Comment by pierDipi** [comment]
Related to https://github.com/knative-extensions/eventing-kafka-broker/issues/4119

**Comment by pierDipi** [comment]
@yuehaii is your issue the same as https://github.com/knative-extensions/eventing-kafka-broker/issues/4119 ?
