### ISSUE TITLE
Controller in version 1.14 opens more and more connections to Kafka cluster

### ISSUE THREAD

**Issue by DFietz** [knative-extensions/eventing-kafka-broker#3999]
**Describe the bug**
With the 1.14 release of the kafka-broker it looks like it ships with a problem related to the connections handling in the kafka controller. 
Over the time the controller uses more and more connections to our kafka cluster. 
In our case it is a managed kafka cluster from Confluent.
We got aware of it as we had a subscription which wasn't forwarding any received events for the subscription/channel.
After investigating we figured out it was caused by a failing vertx http client (java.lang.IllegalStateException: Client is closed). 
The problem could be solved by restarting the channel dispatcher.
After further investigation we figure out the following cause of the failing client:

1. The client was closed due to the subscription wasn't ready and therefore removed from the config. https://github.com/knative-extensions/eventing-kafka-broker/issues/3136

2. The subscription reconcile failed as we where hitting the connection rate limit of our kafka cluster.

3. We where hitting the limit as the kafka controller is opening more and more connections to the kafka cluster. The connections spike every 10 minutes.

4. Restarting the controller resets the connections.

connection metrics from our kafka cluster
![image](https://github.com/user-attachments/assets/13b702ce-e3de-4739-8b1e-075733ac0513)

zoomed in on the 28.06 08:00-09:45
![image](https://github.com/user-attachments/assets/822f1086-2ec3-4e52-8415-2944fecf4808)

used container sockets of the controller (update till rollback)
![image](https://github.com/user-attachments/assets/40495f01-092d-44d8-9de4-b2fcf402d23d)

![image](https://github.com/user-attachments/assets/764af062-9d97-42e6-9843-3a61cca837da)

We have done a rollback (01.07 ~12:00) to the latest 1.13 releases for now to stabilize our system.

 **Expected behavior**
The controller maintains a stable amount of connections as of the 1.13 release.

 **To Reproduce**
The increasing connection count should be visible in version 1.14.5 of the kafka-broker. The connection count should increase slowly. 
The problem occurs in both of our environments QA and Production.

 **Knative release version**
 kafka-broker 1.14.5
 eventing 1.14.2
 serving 1.14.1

 **Additional context**
All the kafka deployments have an istio sidecar injected.

The failing vertx client was a symptom of the failed reconciliation of one of our subscriptions. In addition it looked like the client was "stuck" as the removal of the config causes a non graceful shutdown/removal of the client. The client is reused after the channel got added to the config again.
Let us know if you would need more logs or metrics to investigate.

**Comment by Cali0707** [comment]
Hey @DFietz would you be able to provide logs from the kafka controller (preferrably at the debug level)?

**Comment by matzew** [comment]
@DFietz do you have a lot of different pairs of (`bootstrap server`, `secret`) for each resource?

**Comment by DFietz** [comment]
> Hey @DFietz would you be able to provide logs from the kafka controller (preferrably at the debug level)?
Unfortunately i wasn't able to collect the debug logs as loki was dropping all of them. We did a loki update on the same day :( (defaults changed and drops all logs with 15+ labels)
Do you look for something specific in the debug logs?

> @DFietz can you share how many Knative (mainly Knative Kafka related) resources you have in your cluster?

Prod:
subscriptions 32
channel 32
kafkachannels 32
brokers 19
triggers 32
parallels 0
sequences 28
consumergroups 30
consumers 30

QA:
subscriptions 3
channel 3
kafkachannels 3
brokers 5
triggers 3
parallels 0
sequences 2
consumergroups 3
consumers 3

> @DFietz do you have a lot of different pairs of (`bootstrap server`, `secret`) for each resource?

We have only one bootstrap server and secret configured. I also checked the amount of broker within the kafka clusters.
Both of our envs are running on the same kafka cluster with 12 broker.

**Comment by pierDipi** [comment]
@DFietz the fix is present in the latest 1.14.9 release, have you had a chance to try it out?
