### ISSUE TITLE
ConsumerGroup related SIGSEGV error in kafka-controller

### ISSUE THREAD

**Issue by hosudan** [knative-extensions/eventing-kafka-broker#4003]
**Describe the bug**
I just installed the latest version for knative-kafka-broker and the kafka-controller component keeps crashing.

 **Expected behavior**
To receive a human readable error. I'm unable to figure out where the problem is. 

 **To Reproduce**
[followed the instructions to install the kafka source controller](https://knative.dev/docs/eventing/sources/kafka-source/)

 **Knative release version**
eventing 1.14.5
broker 1.14.7

 **Additional context**
I'm using a confluent kafka cluster. 
I already have a broker which is working perfectly, so the cluster is reachable using the credentials I provided.
I feel like this kafkaClusterAdminClient wasn't properly initialized because I'm missing some configuration, but I don't know which.
Am I supposed to configure the consumergroup in some way? Do I need to specify the bootstrap anywhere else than in kafka-broker/channel configmap? I also tried creating a secret in the default namespace with 'user', 'password' and 'sslType' keys, but it still crashes.

**Logs**
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c6c655]

goroutine 630 [running]:
knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup.(*Reconciler).deleteConsumerGroupMetadata(0xc0000dc2d0, {0x261e178, 0xc001691ce0}, 0xc000004a88)
	knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup/consumergroup.go:304 +0x135
knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup.(*Reconciler).FinalizeKind(0xc0000dc2d0, {0x261e178, 0xc001691ce0}, 0xc000004a88)
	knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup/consumergroup.go:276 +0x5e5
knative.dev/eventing-kafka-broker/control-plane/pkg/client/internals/kafka/injection/reconciler/eventing/v1alpha1/consumergroup.(*reconcilerImpl).Reconcile(0xc000136320, {0x261e178, 0xc001691cb0}, {0xc0010498f0, 0x2c})
	knative.dev/eventing-kafka-broker/control-plane/pkg/client/internals/kafka/injection/reconciler/eventing/v1alpha1/consumergroup/reconciler.go:249 +0x3b8
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc00073b7a0)
	knative.dev/pkg@v0.0.0-20240416145024-0f34a8815650/controller/controller.go:542 +0x508
knative.dev/pkg/controller.(*Impl).RunContext.func3()
	knative.dev/pkg@v0.0.0-20240416145024-0f34a8815650/controller/controller.go:491 +0x59
created by knative.dev/pkg/controller.(*Impl).RunContext in goroutine 601
	knative.dev/pkg@v0.0.0-20240416145024-0f34a8815650/controller/controller.go:489 +0x325

**Comment by pierDipi** [comment]
We merged a fix yesterday https://github.com/knative-extensions/eventing-kafka-broker/pull/4006, fix will be released roughly next Tuesday
