### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by pierDipi** [knative-extensions/eventing-kafka-broker#4008]
**Describe the bug**

There are a few lint errors we need to fix https://github.com/knative-extensions/eventing-kafka-broker/actions/runs/10079854577/job/27868194009?pr=4005

 **Expected behavior**

No lint errors

 **To Reproduce**

Run lint GH action

 **Knative release version**
`main`

 **Additional context**

/good-first-issue

**Comment by rissh** [comment]
Hey @pierDipi ,

I'm planning to work on this issue. Can you please assign me this issue?
Please feel free to provide any suggestions or guidance as I work on this task. I'm open to feedback and would appreciate any insights you might have.

Thank you!

**Comment by ukane-philemon** [comment]
> 'm planning to work on this issue. Can you please assign me this issue?

No one has signified interest before now, you can get the fix ready, PR and cite this issue so @pierDipi can just review the real thing.

**Comment by pierDipi** [comment]
Thanks @rissh, to get the issue assigned to you, you can comment with `/assign` and the bot will assign the issue to you.

Feel free to ask any questions you have directly here
