### ISSUE TITLE
async_prober::probe returns StatusReady instead of StatusUnknown on first invocation

### ISSUE THREAD

**Issue by maschmid** [knative-extensions/eventing-kafka-broker#4012]
**Describe the bug**
The async_prober returns StatusReady instead of StatusUnknown on first invocation

The cache default value per https://github.com/knative-extensions/eventing-kafka-broker/blob/961961c80f862f599c270f03781c4fcac21ba930/control-plane/pkg/prober/async_prober.go#L39

is `Status` , which in 

https://github.com/knative-extensions/eventing-kafka-broker/blob/961961c80f862f599c270f03781c4fcac21ba930/control-plane/pkg/prober/cache.go#L108-L120

means the default value if the key is not in cache, is the default value of `Status` , which is 0, which is `StatusReady`

So when https://github.com/knative-extensions/eventing-kafka-broker/blob/961961c80f862f599c270f03781c4fcac21ba930/control-plane/pkg/prober/async_prober.go#L103-L113 , the `aggregatedCurrentKnownStatus` will be set to StatusReady

This causes the Broker to become Ready briefly before the probe actually probes, so sometimes the Broker is Ready before the dataplane actually is.

 **Expected behavior**
When the Broker is created, it should not be Ready until the probe succeeds.

 **To Reproduce**
Create a namespaced Kafka Broker and immediately watch it's status, e.g. by https://github.com/pulumi/kubespy , 
Sometimes it can be seen that Broker has a Ready status for a brief time, then Unready as the prober fails, and then Ready again for real when the dataplane is actually ready

(the issue seems more reproducible with a namespaced kafka broker, as the dataplane is started just as the broker is created, so it is perhaps more likely the dataplane not being actually ready)

 **Knative release version**
1.14

 **Additional context**
Running on OpenShift, deploying Knative from the https://github.com/openshift-knative/serverless-operator , current `main` branch

**Comment by Cali0707** [comment]
Thanks for finding this @maschmid !

/assign
/triage accepted
